sudo: false
language: node_js
node_js:
  - "stable"

# Since we're caching node_modules we have to clean up stale packages
before_install:
  - npm prune
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang