language: node_js
node_js:
- '5'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_1ce14f3be310_key -iv $encrypted_1ce14f3be310_iv
  -in ./.travis/deploy_key.enc -out ./.travis/deploy_key -d
- npm prune
# encrypted environment variables are not available for pull requests from forks
before_deploy:
- git config user.name "Travis CI"
- git config user.email "notifications@travis-ci.org"
- git checkout master
- git status
- openssl aes-256-cbc -K $encrypted_1ce14f3be310_key -iv $encrypted_1ce14f3be310_iv
  -in ./.travis/deploy_key.enc -out ./.travis/deploy_key -d
- eval "$(ssh-agent -s)"  # start the ssh agent
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy git@github.com:${TRAVIS_REPO_SLUG}.git
cache:
  directories:
  - node_modules
