db:
    image: mongo

roleterminal-vinterland:
    build: .
    environment:
        - DBHOST=db
    links:
        - db
    ports:
        - "8888:8888"
    volumes:
        - images:/usr/src/app/public/images